PIXELAGE_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)

PIXELAGE_BUILDTYPE ?= UNOFFICIAL

PIXELAGE_DISPLAY_VERSION := 2.9

PIXELAGE_PLATFORM_VERSION := 15.0

PIXELAGE_VERSION := ProjectPixelage-v$(PIXELAGE_DISPLAY_VERSION)-$(PIXELAGE_BUILD)-$(PIXELAGE_PLATFORM_VERSION)-$(PIXELAGE_BUILDTYPE)-$(PIXELAGE_BUILD_DATE)

PIXELAGE_SHOW_VERSION := v$(PIXELAGE_DISPLAY_VERSION)-$(PIXELAGE_BUILD)-$(PIXELAGE_BUILDTYPE)-$(PIXELAGE_BUILD_DATE)

# Pixelage Platform Version
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.pixelage.build.date=$(BUILD_DATE) \
    ro.pixelage.build.version=$(PIXELAGE_DISPLAY_VERSION) \
    ro.pixelage.device=$(PIXELAGE_BUILD) \
    ro.pixelage.fingerprint=$(ROM_FINGERPRINT) \
    ro.pixelage.maintainer=$(PIXELAGE_MAINTAINER) \
    ro.pixelage.releasetype=$(PIXELAGE_BUILDTYPE) \
    ro.pixelage.showversion=$(PIXELAGE_SHOW_VERSION) \
    ro.pixelage.version=$(PIXELAGE_VERSION)
